name: Build and Release Plugin ZIP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-release:
    name: Build and Release Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: fregante/daily-version-action@v2
        name: Create tag if necessary
        id: daily-version

      - name: Install Composer dependencies (if needed)
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --prefer-dist
          fi

      - name: Create plugin ZIP file
        run: zip -r wp-s3-sync-plugin.zip . -x "*.git*"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.daily-version.outputs.version }}
          release_name: ${{ steps.daily-version.outputs.version }}
          body: "Release of WP S3 Sync Plugin version ${{ steps.daily-version.outputs.version }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wp-s3-sync-plugin.zip
          asset_name: wp-s3-sync-plugin.zip
          asset_content_type: application/zip
