name: Build Plugin ZIP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Composer dependencies (if needed)
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --prefer-dist
          fi
      - name: Create plugin ZIP file
        run: zip -r wp-s3-sync-plugin.zip . -x "*.git*"
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: wp-s3-sync-plugin-zip
          path: wp-s3-sync-plugin.zip
